2021-11-15 10:50:45,767 INFO    MainThread:35324 [wandb_setup.py:_flush():71] setting env: {}
2021-11-15 10:50:45,767 INFO    MainThread:35324 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-15 10:50:45,768 INFO    MainThread:35324 [wandb_init.py:_log_setup():357] Logging user logs to D:\_jupyter\kaggle\wandb\run-20211115_105045-1wt41g5h\logs\debug.log
2021-11-15 10:50:45,768 INFO    MainThread:35324 [wandb_init.py:_log_setup():358] Logging internal logs to D:\_jupyter\kaggle\wandb\run-20211115_105045-1wt41g5h\logs\debug-internal.log
2021-11-15 10:50:45,768 INFO    MainThread:35324 [wandb_init.py:_jupyter_setup():307] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000015D73085A00>
2021-11-15 10:50:45,769 INFO    MainThread:35324 [wandb_init.py:init():390] calling init triggers
2021-11-15 10:50:45,769 INFO    MainThread:35324 [wandb_init.py:init():395] wandb.init called with sweep_config: {}
config: {}
2021-11-15 10:50:45,769 INFO    MainThread:35324 [wandb_init.py:init():410] re-initializing run, found existing run on stack: 1gdls61m
2021-11-15 10:50:45,771 INFO    MainThread:35324 [wandb_run.py:finish():1347] finishing run bigshanedogg/jigsaw/1gdls61m
2021-11-15 10:50:45,771 INFO    MainThread:35324 [wandb_run.py:_atexit_cleanup():1663] got exitcode: 0
2021-11-15 10:50:45,771 INFO    MainThread:35324 [wandb_run.py:_restore():1635] restore
2021-11-15 10:50:46,655 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 659
  total_bytes: 659
}

2021-11-15 10:50:46,782 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 659
  total_bytes: 659
}

2021-11-15 10:50:47,003 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 659
  total_bytes: 659
}

2021-11-15 10:50:47,447 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 659
  total_bytes: 15489
}

2021-11-15 10:50:47,560 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 659
  total_bytes: 15517
}

2021-11-15 10:50:47,668 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 659
  total_bytes: 15517
}

2021-11-15 10:50:47,774 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 15517
  total_bytes: 15517
}

2021-11-15 10:50:47,893 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 15517
  total_bytes: 15517
}

2021-11-15 10:50:47,999 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 15517
  total_bytes: 15517
}

2021-11-15 10:50:48,105 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 15517
  total_bytes: 15517
}

2021-11-15 10:50:48,210 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 15517
  total_bytes: 15517
}

2021-11-15 10:50:48,657 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 15517
  total_bytes: 15517
}

2021-11-15 10:50:49,157 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 15517
  total_bytes: 15517
}
local_info {
}

2021-11-15 10:50:50,266 INFO    MainThread:35324 [wandb_run.py:_append_files():2061] logging synced files
2021-11-15 10:50:50,270 INFO    MainThread:35324 [wandb_init.py:init():435] starting backend
2021-11-15 10:50:50,270 INFO    MainThread:35324 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=spawn, using: spawn
2021-11-15 10:50:50,273 INFO    MainThread:35324 [backend.py:ensure_launched():199] starting backend process...
2021-11-15 10:50:50,370 INFO    MainThread:35324 [backend.py:ensure_launched():204] started backend process with pid: 13476
2021-11-15 10:50:50,370 INFO    MainThread:35324 [wandb_init.py:init():444] backend started and connected
2021-11-15 10:50:50,380 INFO    MainThread:35324 [wandb_run.py:_label_probe_notebook():866] probe notebook
2021-11-15 10:50:50,381 INFO    MainThread:35324 [wandb_run.py:_label_probe_notebook():876] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-11-15 10:50:50,381 INFO    MainThread:35324 [wandb_init.py:init():503] updated telemetry
2021-11-15 10:50:50,382 INFO    MainThread:35324 [wandb_init.py:init():533] communicating current version
2021-11-15 10:50:51,736 INFO    MainThread:35324 [wandb_init.py:init():538] got version response 
2021-11-15 10:50:51,736 INFO    MainThread:35324 [wandb_init.py:init():548] communicating run to backend with 30 second timeout
2021-11-15 10:50:51,956 INFO    MainThread:35324 [wandb_init.py:init():576] starting run threads in backend
2021-11-15 10:50:56,969 INFO    MainThread:35324 [wandb_run.py:_console_start():1693] atexit reg
2021-11-15 10:50:56,970 INFO    MainThread:35324 [wandb_run.py:_redirect():1567] redirect: SettingsConsole.WRAP
2021-11-15 10:50:56,970 INFO    MainThread:35324 [wandb_run.py:_redirect():1604] Wrapping output streams.
2021-11-15 10:50:56,971 INFO    MainThread:35324 [wandb_run.py:_redirect():1628] Redirects installed.
2021-11-15 10:50:56,971 INFO    MainThread:35324 [wandb_init.py:init():603] run started, returning control to user process
2021-11-15 10:50:57,035 INFO    MainThread:35324 [wandb_init.py:_pause_backend():270] pausing backend
2021-11-15 10:50:57,035 INFO    MainThread:35324 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-15 10:51:40,008 INFO    MainThread:35324 [wandb_init.py:_resume_backend():279] resuming backend
2021-11-15 10:51:42,369 INFO    MainThread:35324 [wandb_init.py:_pause_backend():270] pausing backend
2021-11-15 10:51:42,369 INFO    MainThread:35324 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-15 10:51:48,259 INFO    MainThread:35324 [wandb_init.py:_resume_backend():279] resuming backend
2021-11-15 10:51:48,269 INFO    MainThread:35324 [wandb_setup.py:_flush():71] setting env: {}
2021-11-15 10:51:48,270 INFO    MainThread:35324 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-15 10:51:48,270 INFO    MainThread:35324 [wandb_init.py:_log_setup():357] Logging user logs to D:\_jupyter\kaggle\wandb\run-20211115_105148-2xvg9pc5\logs\debug.log
2021-11-15 10:51:48,270 INFO    MainThread:35324 [wandb_init.py:_log_setup():358] Logging internal logs to D:\_jupyter\kaggle\wandb\run-20211115_105148-2xvg9pc5\logs\debug-internal.log
2021-11-15 10:51:48,270 INFO    MainThread:35324 [wandb_init.py:init():390] calling init triggers
2021-11-15 10:51:48,270 INFO    MainThread:35324 [wandb_init.py:init():395] wandb.init called with sweep_config: {}
config: {}
2021-11-15 10:51:48,271 INFO    MainThread:35324 [wandb_init.py:init():410] re-initializing run, found existing run on stack: 1wt41g5h
2021-11-15 10:51:48,273 INFO    MainThread:35324 [wandb_run.py:finish():1347] finishing run bigshanedogg/jigsaw/1wt41g5h
2021-11-15 10:51:48,273 INFO    MainThread:35324 [jupyter.py:save_history():429] not saving jupyter history
2021-11-15 10:51:48,273 INFO    MainThread:35324 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-15 10:51:48,273 INFO    MainThread:35324 [wandb_init.py:_jupyter_teardown():289] cleaning up jupyter logic
2021-11-15 10:51:48,274 INFO    MainThread:35324 [wandb_run.py:_atexit_cleanup():1663] got exitcode: 0
2021-11-15 10:51:48,274 INFO    MainThread:35324 [wandb_run.py:_restore():1635] restore
2021-11-15 10:51:48,951 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 659
  total_bytes: 659
}

2021-11-15 10:51:49,092 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 659
  total_bytes: 659
}

2021-11-15 10:51:49,323 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 659
  total_bytes: 659
}

2021-11-15 10:51:49,484 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 659
  total_bytes: 15561
}

2021-11-15 10:51:49,597 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 659
  total_bytes: 15588
}

2021-11-15 10:51:49,703 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 659
  total_bytes: 15588
}

2021-11-15 10:51:49,807 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 15588
  total_bytes: 15588
}

2021-11-15 10:51:49,913 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 15588
  total_bytes: 15588
}

2021-11-15 10:51:50,019 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 15588
  total_bytes: 15588
}

2021-11-15 10:51:50,125 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 15588
  total_bytes: 15588
}

2021-11-15 10:51:50,230 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 15588
  total_bytes: 15588
}

2021-11-15 10:51:50,677 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 15588
  total_bytes: 15588
}

2021-11-15 10:51:51,219 INFO    MainThread:35324 [wandb_run.py:_wait_for_finish():1793] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 15588
  total_bytes: 15588
}
local_info {
}

2021-11-15 10:51:52,318 INFO    MainThread:35324 [wandb_run.py:_append_files():2061] logging synced files
